### PR TITLE
Update raven to 5.0.0

### PR DESCRIPTION
**Pull request by mattrobenolt**
cc @alex @ewdurbin

### CODE REVIEW

**Comment by ewdurbin** [comment]
@dpoirier if Sentry is being used for PyCon, you'll want to get this updated (currently merge conflicted on this branch/PR)

**Comment by mattrobenolt** [comment]
Oh man, this is old. We're also on 5.5.0 as of now.

**Comment by dpoirier** [comment]
I'm not sure we're even using this. Wil try to find out.


*Dan Poirier*Developer

dpoirier@caktusgroup.com
www.caktusgroup.com

**Comment by ewdurbin** [comment]
It's a great tool! We should be using! :)

**Comment by dpoirier** [comment]
Upgraded to 5.5.0 in #420.

**Pull request closed without merging**
