### PR TITLE
Nav and CMS Fixes

### PR DESCRIPTION
**Pull request by rayt86**
* [ ] Explore better solution for the account bar on desktop sized screens. I made the account bar a full width bar to distinguish it from the other navigation content.
* [ ] The active nav items' underline extends past the copy. It should end at the last letter of the nav item.
* [ ] Active nav item adds a bottom border to all it's child LIs. Make sure it's only the main nav LI that gets the bottom border on hover/active.
* [ ] On the CMS page, the hills image to the left of the breadcrumbs is a little shorter than the breadcrumb container.

### CODE REVIEW

**Comment by dpoirier** [comment]
When a menu containing the current page is open, the title of the current page has a border line below it completely across the menu, which makes it look (to me) like it's dividing the menu into two parts rather than indicating the current page:

2015-09-11-072405_3280x1200_scrot

**Comment by dpoirier** [comment]
I do see the full-width account bar when logged in. Having the deep red across the top of the page that is otherwise mostly muted greens and blue gives me a vague sense that it's reporting an error of some sort, but that could just be me.

**Comment by dpoirier** [comment]
When logged out, the middles of the login and signup buttons aren't active; I suspect the menu is overlaying the middles of the buttons.

The account bar looks great!

**Comment by dpoirier** [comment]
:shipit:

**Comment by hatlas** [comment]
" The active nav items' underline extends past the copy. It should end at the last letter of the nav item." - this doesn't seem to have been fixed yet.
screen shot 2015-09-16 at 3 41 11 pm

**Pull request merged**
