### PR TITLE
494 Add talk type for Education Summit

### PR DESCRIPTION
**Pull request by dpoirier**
Fixes: #494

### CODE REVIEW

**Comment by dchukhin** [comment]
code looks good; several thoughts:
-do we need to do anything with fixtures?
-the following files have flake8 errors:
    -symposion/reviews/views.py
    -symposion/conference/models.py
    -symposion/reviews/tests.py

**Comment by dpoirier** [comment]
I don't think these fixtures are ever going to be used to start a new conference site from scratch; we just roll over the previous year's database and tweak things.  I'm tempted to just remove the fixture files that aren't needed by tests.

**Comment by dpoirier** [comment]
Fixed flake8 complaints. How does this look?

**Comment by dchukhin** [comment]
:+1:

**Pull request merged**
