### PR TITLE
Design Enhancements

### PR DESCRIPTION
**Pull request by imnikkilee**
Enhancements the usability, responsiveness, and design of the 2018 site. 

### New responsive and keyboard accessible navigation
First off, this navigation is totally responsive. Small screens will see a collapsed menu which they can expand to navigate. (I prefer using the word "Menu" over the hamburger icon as it's been shown that users are more likely to click the word "Menu".)
pycon-mobile-nav

On larger screens, the collapsed menu goes away and we see the standard horizontal menu. I changed the functionality of this a bit, so that the dropdown menus appear on click, rather than on hover. The line between hover-capable devices and touch devices is becoming more and more blurred, and so I find it's best to avoid hover functionality as much as possible so that all users are guaranteed the same, working experience. I've included small arrow icons next to each item as a visual clue so users know that these menu items will expand.
screenshot 2017-09-05 10 44 52

The navigation is totally keyboard accessible. You can tab your way through the primary navigation items, hit "return" to open and close dropdowns, and tab through the dropdown items.

Lastly, we are prepared for situations with no JavaScript. Dropdown navigations typically have to make use of JS, and that's what we're doing here. But in the event that JS is not available, we fall back to a full navigation that is completely styled and usable. It takes up a lot of room, sure, but this is just a fallback that ensures the user can still navigate.
screenshot 2017-09-05 10 47 47

### Responsive header graphic
I updated the home page banner so that the image is responsive and makes use of the screen real estate available.
screenshot 2017-09-05 10 52 40
screenshot 2017-09-05 10 53 02

Other enhancements in the home banner include updated cloud graphics and animation, as well as including the ribbon graphic with the tagline that was in the provided designs. I changed some colors around a bit here. I wasn't sure whether to stay closer to what was already coded on the site or what the provided designs looked like, so I split the difference.

## ~~To Do~~ Done:

- [x] Responsive, accessible, JS-fallback primary navigation
- [x] Responsive header graphic
- [x] New cloud graphics/animation
- [x] Style buttons, forms, account pages, etc..
- [x] Double check styles for the logged-in state of the top banner
- [x] Sticky footer
- [x] Other general CSS tweaks and responsiveness.

^^ Please let me know if there are specifics you'd like added to this list. 💁

### CODE REVIEW

**Comment by ewdurbin** [comment]
seriously only nitpicks, but here's a few things I'd feel more comfortable having you tweak rather than guessing and doing it wrong myself later :-p

- there's a weird in-between width where the "for the community" "by the community" banner is placed side by side rather than stacked, a separator or just forcing stack would be great. 
screen shot 2017-09-05 at 5 46 15 pm
- seems we dropped a little bit of styling that centered headers (h2 specifically) in the content on the home page
screen shot 2017-09-05 at 5 48 16 pm
- overall the clouds feel like they're moving a _bit_ too briskly. something more lackadaisical might keep the header from distracting from content.
- don't forget to add your attribution to the footer :)

🎉 really like the work so far 🎉

**Comment by ewdurbin** [comment]
- The logged in banner cramps user name a tad now at all widths (screen cap is def narrow)

screen shot 2017-09-05 at 5 55 27 pm

- Additionally under extremely narrow width behavior is a bit clunky:

Before:

screen shot 2017-09-05 at 5 57 59 pm


After:

screen shot 2017-09-05 at 5 58 04 pm

**Comment by imnikkilee** [comment]
Also why is this failing ughhh.

**Comment by ewdurbin** [comment]
- did a quick fix for the tests, will resolve _correctly_ after this is merged
- updated the fixtures so if you `make reset` you can now login without creating any accounts as either `admin@example.com` or `user@example.com` with password `None`. Admin is a superuser and User is a regular user. also, the call for proposals are now "open" in local dev so you can fill out a speaker profile then see the proposal form as well.
- the `/account/delete` page was being generated from the `django-user-accounts` module, but I overrided it with a file at `pycon/templates/account/delete.html` that you can customize the markup on.

Overall the refinements are looking great! The _only_ thing that I would wish... could the clouds start their lives somewhere in the background rather than all sliding in from the right? Consider this a "stretch" goal if you have time :)

**Comment by ewdurbin** [comment]
a couple more notes:

- at some widths the site nav gets a bit grumpy with many items (you can see this in staging right now):
screen shot 2017-09-08 at 10 51 53 am

- sponsors section is floating a bit left of center:
screen shot 2017-09-08 at 10 52 53 am

- CMS pages feel a little too far left in wide browser windows:
screen shot 2017-09-08 at 10 53 23 am

**Comment by imnikkilee** [comment]
@ewdurbin Gettin' into that home streeeetttttch! 

- Hit a lot of styles on the deeper forms. Thanks for helping me get to those. I think I can fine tune these a little more still, but they are def getting better.
- Updated cloud animation so clouds start on screen (as you saw on twitter haha)
- Updated CMS content to be centered. I think the sponsors should also be centered now, will have to see when it hits staging.
- Updated the navigation CSS so it's even MORE responsive now. Accounts for any number of items in the nav.
- Looked at some other browsers and everything looking pretty good. 

So yeah, as usual hit me with any more feedback. I wanna give the forms a little more attention before calling this done, but we so so close.

**Comment by ewdurbin** [comment]
@imnikkilee We're looking _great_ I didn't find any issues in Chrome or Safari on OS X, but did try it out on iOS and have two things:

- the "momentum" based scrolling and "scroll-to-top" behavior on iOS seems to be broken.

- buttons in form for speaker profile and sponsor forms on iOS seem to have the native button sneaking out from behind them

img_0190

- still no footer attribution for yourself :)

Aside from that, I'm not seeing anything standing out that classifies as anything beside final polish. Thanks!

**Comment by imnikkilee** [comment]
@ewdurbin Ok pal! Took the WIP label off of this. Hit all your feedback. 

- File inputs are impossible to style cross browser without JS, but I know we don't wanna rely on it too much. (I tried my own hacky solution but as you found out it doesn't really work lol) So went a CSS route that will work on _most_ browsers. On browsers it doesn't work, file input still works perfectly, just will look like a browser standard button.
- Fixed the native mobile safari functionality. Had to do with the sticky-footer code I added, but made some adjustments. 
- Went through and did a little more form fine-tuning. Checked some responsiveness. Styled that WYSIWYG editor that's on some forms cause it was getting ratchet. 
- Added my stamp to the bottom 💁 

Let me know if there's anything else!

**Comment by ewdurbin** [comment]
@imnikkilee thank you!

**Pull request merged**
