### PR TITLE
Registration banner size

### PR DESCRIPTION
**Pull request by rayt86**
Made the size of the registration banner on the homepage scale to the content of the link.

### CODE REVIEW

**Comment by dpoirier** [comment]
Looks good when registration is open.  When registration is coming soon or closed, though, the text is plain black against the dark red banner, not formatted like the registration open text and hard to read.

**Comment by rayt86** [comment]
I added paragraphs to the promo elements that get colored white in the register banner. That should fix the issue with non link elements.

**Comment by dpoirier** [comment]
When registration is open, I see

reg_now


but when it's closed or upcoming, the text is thinner and doesn't look as nice (in my browser):

reg_closed


The text in both cases looks slightly above the centerline of the banner image.

**Comment by rayt86** [comment]
@dpoirier I updated the styling of the p and a elements so the font size issue should be resolved for all states of the registration banner.

**Comment by dpoirier** [comment]
:+1:

**Comment by rayt86** [comment]
@dpoirier I merged changes from develop and fixed the alignment issues with the homepage nav. Do you mind taking another look at this branch before I merge it in.

**Comment by dpoirier** [comment]
The menu alignment issues appear to be fixed.

I'm still seeing a faint color difference between the buildings and the area below them; I don't know if you had tried to fix that here.

**Pull request merged**
