### PR TITLE
393 Send tutorial emails in the background

### PR DESCRIPTION
**Pull request by dpoirier**
Fixes: #393

### CODE REVIEW

**Comment by dpoirier** [comment]
I'll fix the unused import in the factories.py file.

Renaming that method sounds like a good idea; truth in naming!

**Comment by dchukhin** [comment]
looks good!

A thought I had was whether we needed to add any other kind of validation in test_send.py, for example checking if the email has a body, but I guess if the data is taken from a form, then perhaps this kind of check would be redundant

**Comment by dchukhin** [comment]
can we take out commit ba57584?

**Comment by dpoirier** [comment]
Why?  Just catching up with the main development branch to make sure things still work when everything gets merged.

**Comment by dchukhin** [comment]
that makes sense; hmm, something is breaking on my end with a new model

**Comment by dchukhin** [comment]
ok, issue resolved; :+1:

**Pull request merged**
